In [ ]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

In [1]:
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass

In [2]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
print(tf.__version__)

2.4.0


In [3]:
dataset = tf.data.Dataset.range(10)
for val in dataset:
   print(val.numpy())

0
1
2
3
4
5
6
7
8
9


In [4]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, stride=2)  # Gets every second item
for window_dataset in dataset:
  for val in window_dataset:
    print(val.numpy(), end=" ")
  print()

0 2 4 6 8 
1 3 5 7 9 
2 4 6 8 
3 5 7 9 
4 6 8 
5 7 9 
6 8 
7 9 
8 
9 


In [13]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
for window_dataset in dataset:
  print(type(window_dataset), len(window_dataset))
  for val in window_dataset:
    print(val.numpy(), end=" ")
  print()

<class 'tensorflow.python.data.ops.dataset_ops._VariantDataset'> 5
0 1 2 3 4 
<class 'tensorflow.python.data.ops.dataset_ops._VariantDataset'> 5
1 2 3 4 5 
<class 'tensorflow.python.data.ops.dataset_ops._VariantDataset'> 5
2 3 4 5 6 
<class 'tensorflow.python.data.ops.dataset_ops._VariantDataset'> 5
3 4 5 6 7 
<class 'tensorflow.python.data.ops.dataset_ops._VariantDataset'> 5
4 5 6 7 8 
<class 'tensorflow.python.data.ops.dataset_ops._VariantDataset'> 5
5 6 7 8 9 


In [15]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))  # Take a number of datasets, and combine them into one master dataset
for window in dataset:
  print(type(window), len(window))
  print(window.numpy())


<class 'tensorflow.python.framework.ops.EagerTensor'> 5
[0 1 2 3 4]
<class 'tensorflow.python.framework.ops.EagerTensor'> 5
[1 2 3 4 5]
<class 'tensorflow.python.framework.ops.EagerTensor'> 5
[2 3 4 5 6]
<class 'tensorflow.python.framework.ops.EagerTensor'> 5
[3 4 5 6 7]
<class 'tensorflow.python.framework.ops.EagerTensor'> 5
[4 5 6 7 8]
<class 'tensorflow.python.framework.ops.EagerTensor'> 5
[5 6 7 8 9]


In [17]:
 dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))  # Convert into features and label
for x,y in dataset:
  print(x.numpy(), y.numpy())

[0 1 2 3] [4]
[1 2 3 4] [5]
[2 3 4 5] [6]
[3 4 5 6] [7]
[4 5 6 7] [8]
[5 6 7 8] [9]


In [19]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=10)
for x,y in dataset:
  print(x.numpy(), y.numpy())


[3 4 5 6] [7]
[2 3 4 5] [6]
[0 1 2 3] [4]
[5 6 7 8] [9]
[1 2 3 4] [5]
[4 5 6 7] [8]


In [21]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=10)
dataset = dataset.batch(2).prefetch(1)  # Batch the dataset into groups of 2
for x,y in dataset:
  print("x = ", x.numpy())
  print("y = ", y.numpy())


x =  [[3 4 5 6]
 [5 6 7 8]]
y =  [[7]
 [9]]
x =  [[1 2 3 4]
 [2 3 4 5]]
y =  [[5]
 [6]]
x =  [[4 5 6 7]
 [0 1 2 3]]
y =  [[8]
 [4]]
