In [1]:
import numpy as np
import tensorflow as tf

In [3]:
x = tf.constant(3)

In [6]:
tf.executing_eagerly()

True

In [7]:
x

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [9]:
print(x)

tf.Tensor(3, shape=(), dtype=int32)


In [10]:
x.dtype

tf.int32

In [11]:
x.shape

TensorShape([])

In [12]:
x.numpy()

3

In [13]:
x+5

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [23]:
x1 = tf.constant([1.1, 2.2, 3.3, 4.4])

In [24]:
x1 + 5

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([6.1, 7.2, 8.3, 9.4], dtype=float32)>

In [25]:
x1 + x

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([2.2, 4.4, 6.6, 8.8], dtype=float32)>

In [27]:
tf.add(x1, x1)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([2.2, 4.4, 6.6, 8.8], dtype=float32)>

In [28]:
x1+x1

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([2.2, 4.4, 6.6, 8.8], dtype=float32)>

In [32]:
x2 = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8]])
x2

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)>

In [34]:
x2 = tf.cast(x2, tf.float32)
x2

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float32)>

In [37]:
x1 + x2

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 2.1,  4.2,  6.3,  8.4],
       [ 6.1,  8.2, 10.3, 12.4]], dtype=float32)>

In [38]:
x2 + x1

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 2.1,  4.2,  6.3,  8.4],
       [ 6.1,  8.2, 10.3, 12.4]], dtype=float32)>

In [39]:
tf.multiply(x1, x2)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 1.1     ,  4.4     ,  9.9     , 17.6     ],
       [ 5.5     , 13.200001, 23.1     , 35.2     ]], dtype=float32)>

In [40]:
tf.multiply(x2, x1)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 1.1     ,  4.4     ,  9.9     , 17.6     ],
       [ 5.5     , 13.200001, 23.1     , 35.2     ]], dtype=float32)>

In [41]:
x1.numpy()

array([1.1, 2.2, 3.3, 4.4], dtype=float32)

In [47]:
np_x4 = np.array([[1, 2], [3, 4], [4, 5]])
np_x4

array([[1, 2],
       [3, 4],
       [4, 5]])

In [48]:
x4 = tf.convert_to_tensor(np_x4)
x4

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[1, 2],
       [3, 4],
       [4, 5]])>

In [49]:
np.square(x2)

array([[ 1.,  4.,  9., 16.],
       [25., 36., 49., 64.]], dtype=float32)

In [50]:
np.sqrt(x2)

array([[1.       , 1.4142135, 1.7320508, 2.       ],
       [2.236068 , 2.4494898, 2.6457512, 2.828427 ]], dtype=float32)

In [51]:
# Numpy operations are not part of the TF computation graph! Prefer to use tf

In [52]:
tf.is_tensor(1)

False

In [53]:
tf.is_tensor(x2)

True

In [54]:
tf.is_tensor(np_x4)

False

In [56]:
tf.zeros([3, 4], tf.int32)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>

In [57]:
tf.ones([3, 4], tf.int32)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)>

In [60]:
tf.reshape(tf.ones([3, 4], tf.int32), [2, 2, 3])

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]], dtype=int32)>