In [1]:
import numpy as np
import tensorflow as tf

In [2]:
x = tf.constant(3)

In [3]:
tf.executing_eagerly()

True

In [4]:
x

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [5]:
print(x)

tf.Tensor(3, shape=(), dtype=int32)


In [6]:
x.dtype

tf.int32

In [7]:
x.shape

TensorShape([])

In [8]:
x.numpy()

3

In [9]:
x+5

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [10]:
x1 = tf.constant([1.1, 2.2, 3.3, 4.4])

In [11]:
x1 + 5

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([6.1, 7.2, 8.3, 9.4], dtype=float32)>

In [16]:
x1 + x1

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([2.2, 4.4, 6.6, 8.8], dtype=float32)>

In [17]:
tf.add(x1, x1)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([2.2, 4.4, 6.6, 8.8], dtype=float32)>

In [18]:
x1+x1

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([2.2, 4.4, 6.6, 8.8], dtype=float32)>

In [19]:
x2 = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8]])
x2

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)>

In [20]:
x2 = tf.cast(x2, tf.float32)
x2

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float32)>

In [21]:
x1 + x2

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 2.1,  4.2,  6.3,  8.4],
       [ 6.1,  8.2, 10.3, 12.4]], dtype=float32)>

In [22]:
x2 + x1

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 2.1,  4.2,  6.3,  8.4],
       [ 6.1,  8.2, 10.3, 12.4]], dtype=float32)>

In [23]:
tf.multiply(x1, x2)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 1.1     ,  4.4     ,  9.9     , 17.6     ],
       [ 5.5     , 13.200001, 23.1     , 35.2     ]], dtype=float32)>

In [24]:
tf.multiply(x2, x1)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 1.1     ,  4.4     ,  9.9     , 17.6     ],
       [ 5.5     , 13.200001, 23.1     , 35.2     ]], dtype=float32)>

In [25]:
x1.numpy()

array([1.1, 2.2, 3.3, 4.4], dtype=float32)

In [26]:
np_x4 = np.array([[1, 2], [3, 4], [4, 5]])
np_x4

array([[1, 2],
       [3, 4],
       [4, 5]])

In [27]:
x4 = tf.convert_to_tensor(np_x4)
x4

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[1, 2],
       [3, 4],
       [4, 5]])>

In [28]:
np.square(x2)

array([[ 1.,  4.,  9., 16.],
       [25., 36., 49., 64.]], dtype=float32)

In [29]:
np.sqrt(x2)

array([[1.       , 1.4142135, 1.7320508, 2.       ],
       [2.236068 , 2.4494898, 2.6457512, 2.828427 ]], dtype=float32)

In [30]:
# Numpy operations are not part of the TF computation graph! Prefer to use tf

In [31]:
tf.is_tensor(1)

False

In [32]:
tf.is_tensor(x2)

True

In [33]:
tf.is_tensor(np_x4)

False

In [34]:
tf.zeros([3, 4], tf.int32)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>

In [35]:
tf.ones([3, 4], tf.int32)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)>

In [36]:
tf.reshape(tf.ones([3, 4], tf.int32), [2, 2, 3])

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]], dtype=int32)>

In [41]:
# Variables
v1 = tf.Variable([[1, 2, 3], [4.5, 2, 7]])
v1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1. , 2. , 3. ],
       [4.5, 2. , 7. ]], dtype=float32)>

In [54]:
v2 = tf.Variable([[2, 1.1, 3], [3, 4, 334]])
v2

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  2. ,   1.1,   3. ],
       [  3. ,   4. , 334. ]], dtype=float32)>

In [55]:
tf.add(v1, v2)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[  3. ,   3.1,   6. ],
       [  7.5,   6. , 341. ]], dtype=float32)>

In [56]:
tf.convert_to_tensor(v1) + tf.convert_to_tensor(v2)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[  3. ,   3.1,   6. ],
       [  7.5,   6. , 341. ]], dtype=float32)>

In [53]:
x1 = tf.constant([1, 2])
x2 = tf.constant([1.1, 2.2])
tf.cast(x1, tf.float32)+x2

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.1, 4.2], dtype=float32)>

In [57]:
v1.assign([[100, 200, 300], [400, 500, 600]])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[100., 200., 300.],
       [400., 500., 600.]], dtype=float32)>

In [59]:
v1[0, 0].assign(101)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[101., 200., 300.],
       [400., 500., 600.]], dtype=float32)>

In [61]:
v1.assign_add(v2)
v1.assign_add(v2)
v1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 105.     ,  202.20001,  306.     ],
       [ 406.     ,  508.     , 1268.     ]], dtype=float32)>

In [62]:
v1.assign_sub(v1)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [63]:
v1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [64]:
v3 = tf.Variable(v2)

In [66]:
v3.assign([[100, 200, 300], [1, 2, 3]])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[100., 200., 300.],
       [  1.,   2.,   3.]], dtype=float32)>

In [67]:
v3

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[100., 200., 300.],
       [  1.,   2.,   3.]], dtype=float32)>

In [68]:
v2

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  2. ,   1.1,   3. ],
       [  3. ,   4. , 334. ]], dtype=float32)>

In [74]:
# Eager execution vs. Static
a = tf.constant(5, name="a")
b = tf.constant(6, name="b")
c = tf.add(a, b, name="c")
tf.compat.v1.executing_eagerly()

True

In [73]:
s = tf.compat.v1.Session()
s.run(c)
# Since we have eager execution, there is no graph to execute!

RuntimeError: The Session graph is empty.  Add operations to the graph before calling run().

In [75]:
# Let's try that again, after disabling eager execution
tf.compat.v1.disable_eager_execution()
tf.compat.v1.executing_eagerly()

False

In [76]:
tf.compat.v1.reset_default_graph()

In [78]:
e = tf.constant(5, name="e")
f = tf.constant(7, name="f")
g = tf.add(e, f, name="sum")
g

<tf.Tensor 'sum_1:0' shape=() dtype=int32>

In [79]:
s = tf.compat.v1.Session()
s.run(g)

12

In [82]:
s.close()

In [87]:
m = tf.Variable([1.0, 2.0], tf.float32, name="m")
n = tf.Variable([3.0, 5.0], tf.float32, name="n")
# In TF 1.0, the values are not initialized until the graph executes.
n

<tf.Variable 'n_2:0' shape=(2,) dtype=float32>

In [100]:
# Input values are specified as placeholders
x = tf.compat.v1.placeholder(tf.float32, shape=[2,], name="x")
x

<tf.Tensor 'x_1:0' shape=(2,) dtype=float32>

In [89]:
y = m * x + n
y

<tf.Tensor 'add:0' shape=(2,) dtype=float32>

In [90]:
init = tf.compat.v1.global_variables_initializer()  # Required to initialize the variables with their values

In [96]:
with tf.compat.v1.Session() as sess:
    sess.run(init)
    y_out = sess.run(y, feed_dict={x: [100.0, 100.0]})
    print(y_out, type(y_out))
    writer = tf.compat.v1.summary.FileWriter('./logs', sess.graph)
    writer.close()

[103. 205.] <class 'numpy.ndarray'>
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
tf.float32 has type DType, but expected one of: int, long, bool
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
tf.float32 has type DType, but expected one of: int, long, bool


In [97]:
%load_ext tensorboard

In [99]:
%tensorboard --logdir="./logs" --port 6060